<!DOCTYPE html>
<html lang="en">
<head>
  <title>Fooduncle.com</title>

  
  <link rel="stylesheet" href="assets\css\aos.css" >
  
  
  
  <style>
	body{
		/* suppose you want minimun width of 1000px */
	 min-width:600px !important;
	   
	}
	.row
		{
			
			
			min-width:600px !important;
			margin:auto !important;
			
			background-color:#011547;
			width: 70% ;
			margin:auto; 
			padding:40px 40px 40px 40px; 
			border-radius:20px;
			min-width:275px;
			
			
		}
	
		textarea {
			
  width: 95% !important; 
  max-height:300px;
  height: 200px !important;
}
body{
		background-color:#cdcff7!important ;
	}
.btn
	{
		background-color:#2b6fe5 !important ;
	}
.text
{
	color:#f7f74c;
}
p{
	color:white;
}
														
  </style>
  
</head>
<body>
<!-- NAVIGATION BAR CONTENT-->
<?php include'header.php'?>
<?php include'navbar.php'?>
	<!-- Profile        box code-->

				
				<br><br><br>

	<div class="container" >
		<div class="row" >
		
		<div class="heading" align="center" style="margin:5px 5px 5px 5px;">
		<span style="color:white ;font-family: arial;font-size:3em;font-wieght:bold;" data-aos="zoom-in"><u>How It Works</u></span><br><br>
		</div>
		<div class="que" align="left" style="font-size:1em;" data-aos="fade-right">
		<span style="color:#fff468 ;font-weight:400"># Online Exam Portal</span><br><br>
			<p>This portal helps you to test your preparation for your upcoming test.It also give a brief report how you performed in your test.  </p><br><br>
			
		</div>
		<br>
		<div class="que" align="left" style="font-size:1em;" data-aos="fade-left">
		<span style="color:#fff468 ;font-weight:400"># How To Create Account</span><br>
		<p>To create account ,Find SignUp button on navigation bar then A pop-up will appear which require's
		your details ,Make sure that you provide correct details and fill each field,Press SUBMIT button.
		<br><br>
		
		SignUp(navigation bar) > FILL DETAILS > SUBMIT<br><br>
		</p>
		
			
		</div>
		<br>
		<div class="que" align="left" style="font-size:1em;" data-aos="fade-right">
		<span style="color:#fff468 ;font-weight:400"># How To Login Into Account</span><br>
		<p>To Login ,Find Login button on navigation bar .A pop up comes out,fill required
		details,then click Submit.
		<br><br>
		Login(navigation bar) >  FILL DETAILS > SUBMIT
		<br><br></p>
		
				   
		</div>
		<br>
		<div class="que" align="left" style="font-size:1em;" data-aos="fade-left">
		<span style="color:#fff468 ;font-weight:400"># Download Your Analysis Report</span><br>
		<p>After you submit your test ,three PDF will be generated by the system which consists of Question booklet,Question booklet with answers,
		Wrong attempt book (Speciality of ExamUncle). 
		<br><br>
		
		
			   
		</div>
		<br>
		<!--
		<div class="que" align="left" style="font-size:1em;" data-aos="fade-right" >
		<span style="color:#fff468 ;font-weight:400"># How to Update Profile</span><br>
			
		
				   
		</div>
		<br>
		<div class="que" align="left" style="font-size:1em;" data-aos="fade-left">
		<span style="color:#fff468 ;font-weight:400"># How to Reset Password</span><br>
			
			
				   
		</div>
		<br>
		<div class="que" align="left" style="font-size:1em;" data-aos="fade-right" >
		<span style="color:#fff468 ;font-weight:400"># How to Delete Feedback</span><br>
				   
		</div>
		<br><br>
		-->
		</div>
	</div>
	<br><br><br>
				
						
															

<?php include'footer.php'?>

<script src="assets\js\aos.js" type="text/javascript"></script>
<script>
		AOS.init({
  duration: 1500,
})
  </script>

</body>
</html>
